### ISSUE TITLE
Add build script for releaseses

### ISSUE THREAD

**Issue by vijayiyer05** [emeyers/Brain-Observatory-Toolbox#169]
Suggest to add a build script using the [build tool](https://www.mathworks.com/help/matlab/ref/buildtool.html) which covers the following steps:

- Running the example live scripts so they all show their outputs
- Bumping the release number in Contents.m (useful for showcasing compute environment in [DandiHub](https://hub.dandiarchive.org/))

**Comment by vijayiyer05** [comment]
@ehennestad: one thing discussed in the overview by @bpancras at the recent "campfire chat" was the build tool. 
This issue raised last year suggested some low-hanging fruit this system could help to achieve in the BOT context. 
Maybe useful as a quick way to get familiar with it.

**Comment by ehennestad** [comment]
Yes, this should be straight-forward.

A couple of questions:
I know you can run export(..., Run=true) to run livescripts and they will show their outputs. Also, I have found the internal function `matlab.internal.liveeditor.executeAndSave` which is useful if you don't need to save. Do you know of any non-internal methods for doing this?

Also, maybe more important. I wanted to export a live script using a GitHub action, but got the following error:
```
 {Error using matlab.internal.cef.webwindow
  DISPLAY environment variable must be set to a valid X11 display.
  
  Error in matlab.internal.liveeditor.LiveEditorUtilities.createDocument (line 26)
      webWindow = matlab.internal.cef.webwindow(url, matlab.internal.getDebugPort);
  
  Error in matlab.internal.liveeditor.LiveEditorUtilities.open>openUsingCEF (line 100)
                  LiveEditorUtilities.createDocument(timeout,webWindow);
  
  Error in matlab.internal.liveeditor.LiveEditorUtilities.open (line 33)
      [javaRichDocument, cleanupObj, webWindow] = openUsingCEF(fileName, reuse, timeout, webWindow);
  
  Error in export (line 116)
          matlab.internal.liveeditor.LiveEditorUtilities.open(...

```

The workflow runs on `ubuntu-latest`

Any ideas if that would be possible?

**Comment by vijayiyer05** [comment]
Thanks @ehennestad  for elaborating. That's what I guessed the application would be! 

Generally my opinion is: a build script seems heavyweight solely for the purpose of making live scripts viewable/linkable. 

Wrt the File Exchange rendered versions, they are linkable in my hands, by using "Copy Link Address" from the browser. Can you see this on a second look? 

That said, I recognize this is not elegant, and it's only sensible to update this link on the README at release versions, not at every commit. Given that there are other reasons for the build script (as listed above), I'm good with exporting to MD and/or HTML as an additional benefit: stable links for each of the rendered examples.

**Comment by ehennestad** [comment]
> Generally my opinion is: a build script seems heavyweight solely for the purpose of making live scripts viewable/linkable. 
Just out of curiosity, heavyweight in what sense?

> Wrt the File Exchange rendered versions, they are linkable in my hands, by using "Copy Link Address" from the browser. Can you see this on a second look? 

Yes I see it now. Then I would suggest to update the links for the FileExchange badges in the readme tables point directly to the tutorials and not the main FileExchange page for the BOT

**Comment by vijayiyer05** [comment]
> Yes I see it now:) Then I would suggest to update the links for the FileExchange badges in the readme tables to point directly to the tutorials and not the main FileExchange page for the BOT

I encourage that update! 

> Just out of curiosity, heavyweight in what sense?
There's a class of user for whom GitHub is second nature but GitHub Actions is next level. I'm a bit queasy if rendering (which FX provides) is the reason they have to go through that transition. Imagine the experimental scientist (not a toolbox author) publishing the code for their figure publication on GitHub as part of an open science practice. I'd like to encourage them to use a live script to make it expository, without requiring them to learn/use GitHub Actions to make it broadly visible.

**Comment by mcafaro** [comment]
Regarding exporting live scripts in GitHub Actions: The `export` function requires the machine have a display but GitHub-hosted Linux runners do not provide a display by default.

You can set up a virtual display on GitHub-hosted Linux runners by using Xvfb display server to enable functions like `export` to work. Please see the example below:

```yaml
name: Use Virtual Display on Linux Runner
on: [push]
jobs:
  my-job:
    name: Test an App
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Start virtual display server
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run MATLAB
         uses: matlab-actions/run-command@v2
         with:
           command: export("sample.mlx");
```
